version: "3.7"
services:
  app:
    build:
      context: .
    image: auth-example
    container_name: app
    ports:
      - 5000:5000
    volumes:
      - ./src:/home/app/src
    environment:
      - HOST=postgres
  postgres:
    image: postgres:13
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - ./initdb/scripts:/docker-entrypoint-initdb.d
      - ./initdb/csv:/tmp
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=password
